#-*- mode: org -+-
#+COLUMNS: %Date(Date) %10TODO %7Clocksum(Clock) %12ITEM %8Effort(Effort){:} %5TAGS %SCHEDULED
#+TITLE: Tiny-MLOps: a framework for orchestrating ML applications at the far edge of IoT systems
#+DESCRIPTION: Hoping you can assist, there is a pre-arb that has been unable to be processed in VANS (no claim ID appearing). I have processed this manually in CM but wanted to raise a ticket for you to create the pre-arb in VANS please. 
#+COLUMNS: %Date(Date) %10TODO %7Clocksum(Clock) %12ITEM %8Effort(Effort){:} %5TAGS %SCHEDULED

* TODO Paper 13 MLOps Challenges in Multi-Organization Setup
:LOGBOOK:
CLOCK: [2023-09-06 Wed 15:45]--[2023-09-06 Wed 16:18] =>  0:33
:END:
** Challenges
*** Limited hardware and software capabilities of far edge devices usually prevent adopting any of these MLOps tools and practices within the lowest layers of an IoT technology stack
*** Loading in memory of the model for Iot devices may saturate the device memory or take a long time, even minutes
*** missing ground truth for exploiting the locality of devices to better learn from the surrounding environment
*** access to the monitored asset is difficult after deployment
** TODO Benefit
*** Far edge devices
*** Exploiting the locality of devices to better learn from the surrounding environment
*** Pool of models can perform Feature engineering
*** Detect when a model in production fails
**** The Pool Inference Engine keeps monitoring the detection performance of the Champion model deployed in the embedded device. If the Champion model starts to fail ( e.g., the number of false-positive detection in a time window is above a threshold), the Pool Inference Engine can trigger the replacement of the Champion model to improve the system’s performance.
** TODO Tool
** TODO Approach
*** Tiny-MLOps
*** Machine Learning Model Operationalization Management
*** Reduced resources available onboard typical IoT devices
*** Software engineer and operational engineering and data scientists focus on different phases of the MLops lifecycle.
*** change some run-time parameters of the model (e.g. decision thresholds)
*** Using an IoT gateway
*** Sensors
** TODO Metrics


Machine Learning Model Operationalization Management
